# Generated by Django 5.2.4 on 2025-08-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_remove_surveyresponse_mentalbert_prediction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyresponse",
            name="mentalbert_prob",
            field=models.FloatField(default=0.01),
        ),
    ]
